recomenderNameCPName: Recommender Name
recomenderNameReportConfig: Recommender Name
recomendationDoctypes:
  - Letter of Recomendation
  - Letter of Rec BUA
  - Letter of Rec LUA
  - Letter of Rec DUA