reportName: WADOC
reportDescription: Undergraduate/Graduate Web Application Uploads
csvFilePath: Y:\import_agent\DI_###ENV_U3###_SA_AD_INBOUND\
csvArchivePath: Y:\import_agent\DI_###ENV_U3###_SA_AD_INBOUND\csv_archive\
errorQueue: Import Split Index Error
ignoreFinalPage: false
copyFinalPageToChildren: false
tempQueue: Import Split Index Working
finalQueue: Import Split Index Complete
backupQueue: Import Split Index Archive

staticValues:
  - name: f5
    type: IDX
    transform: getF5DateTime
  - name: SA Application Nbr
    type: CP
    value:
  - name: Source
    type: CP
    value: SA Web Application
  - name: Document App Plan
    type: CP
    value: import-split-index.js iScript
  - name: copy recomender name to letter of recomender
    type: none
    transform: checkForRecomendationAD

fileNameValues:
  - name: reportName
    type: none
  - name: Web Rec Number
    type: none
  - name: Document Type
    type: IDX
    transform: lookupDrawerDoctypeAD

csvValues:
  - name: pages
    type: NONE
  - name: Institution
    type: NONE
  - name: Career
    type: none
    transform: populateCareer
  - name: App Center
    type: CP
  - name: folder
    type: IDX
  - name: tab
    type: IDX
  - name: f3
    type: IDX
  - name: Term Code
    type: CP
  - name: Program
    type: CP
  - name: Program Code
    type: CP
  - name: Plan
    type: CP
  - name: Plan Code
    type: CP
  - name: Sub-Plan
    type: CP
  - name: Sub-Plan Code
    type: CP
  - name: F4
    type: IDX
    transform: ugrdToGrad
  - name: External App Nbr
    type: CP
  - name: Alias 1
    type: CP
  - name: Alias 2
    type: CP
  - name: Alias 3
    type: CP
  - name: Alias 4
    type: CP
  - name: Recommender Name
    type: none
