// webAppsummarydoctypedrawerlookup
// dependencies: 
// Inputs:
//	STAGE_NOT_USED.Institution
//	STAGE_NOT_USED.Career
//	CUR_CFG.reportName
//	STAGE_PROPS['App Center']
//
// Outputs:
//	STAGE_KEYS.docType
//	STAGE_KEYS.drawer

// Enter mapping configuration here for use in the lookupDrawerDoctypeAD helper function
//
// The function will look at the report type, staged doctype, Insitution, Career,
// and Application Center to determine what doctype and drawer to apply to the document
//
// # Web application summary report from PeopleSoft
// zadr0257-1:
//   stagedDoctype: Admissions Application // make optional
//   doctype code: Admissions Application
//   Institution: UMBOS
//   Career: UGRD
//   App Center: UGRD
//   doctype: Resume BUA
//   drawer: UMBUA
//
// SA web application supplemental uploaded documents

global.CFG = {};
global.CFG.lookupDrawerDoctypeAD_config = { 'zadr0257-1':
   [ { institution: 'UMBOS',
       career: 'UGRD',
       appCenter: 'UGRD',
       doctype: 'App - Web/Common App Summary BUA',
       drawer: 'UMBUA' },
     { institution: 'UMBOS',
       career: 'GRAD',
       appCenter: 'GRAD',
       doctype: 'Application Graduate Admissions',
       drawer: 'UMBGA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'UGRD',
       doctype: 'App - Web/Common App Summary DUA',
       drawer: 'UMDUA' },
     { institution: 'UMDAR',
       career: 'GRAD',
       appCenter: 'GRAD',
       doctype: 'Application Graduate Admissions',
       drawer: 'UMDGA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'CNOW',
       doctype: 'App - Web/Common App Summary DUA',
       drawer: 'UMDUA' },
     { institution: 'UMLOW',
       career: 'UGRD',
       appCenter: 'UGRD',
       doctype: 'App - Web/Common App Summary LUA',
       drawer: 'UMLUA' },
     { institution: 'UMLOW',
       career: 'GRAD',
       appCenter: 'GRAD',
       doctype: 'Application Graduate Admissions',
       drawer: 'UMLGA' },
     { institution: 'UMLOW',
       career: 'CSCE',
       appCenter: 'CSCE',
       doctype: 'App - Web/Common App Summary LUA',
       drawer: 'UMLUA' } ],
  'zadr0257-2':
   [ { institution: 'UMBOS',
       career: 'UGRD',
       appCenter: 'UGRD',
       doctype: 'PD Summary (PS Report) BUA',
       drawer: 'UMBUA Lockbox' },
     { institution: 'UMBOS',
       career: 'GRAD',
       appCenter: 'GRAD',
       doctype: 'Personal Disclosure Question',
       drawer: 'UMBGA Lockbox' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'UGRD',
       doctype: 'PD Question (Web) DUA',
       drawer: 'UMDUA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'CNOW',
       doctype: 'PD Question (Web) DUA',
       drawer: 'UMDUA' },
     { institution: 'UMDAR',
       career: 'GRAD',
       appCenter: 'GRAD',
       doctype: 'Personal Disclosure Question',
       drawer: 'UMDGA Lockbox' },
     { institution: 'UMLOW',
       career: 'UGRD',
       appCenter: 'UGRD',
       doctype: 'PD Summary (PS Report) LUA',
       drawer: 'UMLUA Lockbox' },
     { institution: 'UMLOW',
       career: 'GRAD',
       appCenter: 'GRAD',
       doctype: 'Personal Disclosure Question',
       drawer: 'UMLGA Lockbox' },
     { institution: 'UMLOW',
       career: 'CSCE',
       appCenter: 'CSCE',
       doctype: 'PD Summary (PS Report) LUA',
       drawer: 'UMLUA Lockbox' } ],
  'zadr257a-1':
   [ { institution: 'UMBOS',
       career: 'UGRD',
       appCenter: 'UGRD',
       doctype: 'App - Web/Common App Summary BUA',
       drawer: 'UMBUA' },
     { institution: 'UMBOS',
       career: 'GRAD',
       appCenter: 'GRAD',
       doctype: 'Application Graduate Admissions',
       drawer: 'UMBGA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'UGRD',
       doctype: 'App - Web/Common App Summary DUA',
       drawer: 'UMDUA' },
     { institution: 'UMDAR',
       career: 'GRAD',
       appCenter: 'GRAD',
       doctype: 'Application Graduate Admissions',
       drawer: 'UMDGA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'CNOW',
       doctype: 'App - Web/Common App Summary DUA',
       drawer: 'UMDUA' },
     { institution: 'UMLOW',
       career: 'UGRD',
       appCenter: 'UGRD',
       doctype: 'App - Web/Common App Summary LUA',
       drawer: 'UMLUA' },
     { institution: 'UMLOW',
       career: 'GRAD',
       appCenter: 'GRAD',
       doctype: 'Application Graduate Admissions',
       drawer: 'UMLGA' },
     { institution: 'UMLOW',
       career: 'CSCE',
       appCenter: 'CSCE',
       doctype: 'App - Web/Common App Summary LUA',
       drawer: 'UMLUA' } ],
  'zadr257a-2':
   [ { institution: 'UMBOS',
       career: 'UGRD',
       appCenter: 'UGRD',
       doctype: 'PD Summary (PS Report) BUA',
       drawer: 'UMBUA Lockbox' },
     { institution: 'UMBOS',
       career: 'GRAD',
       appCenter: 'GRAD',
       doctype: 'Personal Disclosure Question',
       drawer: 'UMBGA Lockbox' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'UGRD',
       doctype: 'PD Question (Web) DUA',
       drawer: 'UMDUA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'CNOW',
       doctype: 'PD Question (Web) DUA',
       drawer: 'UMDUA' },
     { institution: 'UMDAR',
       career: 'GRAD',
       appCenter: 'GRAD',
       doctype: 'Personal Disclosure Question',
       drawer: 'UMDGA Lockbox' },
     { institution: 'UMLOW',
       career: 'UGRD',
       appCenter: 'UGRD',
       doctype: 'PD Summary (PS Report) LUA',
       drawer: 'UMLUA Lockbox' },
     { institution: 'UMLOW',
       career: 'GRAD',
       appCenter: 'GRAD',
       doctype: 'Personal Disclosure Question',
       drawer: 'UMLGA Lockbox' },
     { institution: 'UMLOW',
       career: 'CSCE',
       appCenter: 'CSCE',
       doctype: 'PD Summary (PS Report) LUA',
       drawer: 'UMLUA Lockbox' } ],
  zadr0244:
   [ { institution: 'UMBOS',
       career: 'UGRD',
       appCenter: 'UGRD',
       doctype: 'Test Score Report Undergraduate',
       drawer: 'UMBUA' },
     { institution: 'UMBOS',
       career: 'GRAD',
       appCenter: 'GRAD',
       doctype: 'Test Score Report',
       drawer: 'UMBGA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'UGRD',
       doctype: 'New Test Scores DUA',
       drawer: 'UMDUA' },
	   { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'CNOW',
       doctype: 'New Test Scores DUA',
       drawer: 'UMDUA' },
     { institution: 'UMDAR',
       career: 'GRAD',
       appCenter: 'GRAD',
       doctype: 'Test Score Report',
       drawer: 'UMDGA' },
     { institution: 'UMLOW',
       career: 'UGRD',
       appCenter: 'UGRD',
       doctype: 'Test Score Report Undergraduate',
       drawer: 'UMLUA' },
     { institution: 'UMLOW',
       career: 'GRAD',
       appCenter: 'GRAD',
       doctype: 'Test Score Report',
       drawer: 'UMLGA' } ],
  WADOC:
   [ { institution: 'UMBOS',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'RESUM',
       doctype: 'Resume BUA',
       drawer: 'UMBUA' },
     { institution: 'UMBOS',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'PSTMT',
       doctype: 'Personal Statement BUA',
       drawer: 'UMBUA' },
     { institution: 'UMBOS',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'DISCL',
       doctype: 'PD Statement (PD1) BUA',
       drawer: 'UMBUA Lockbox' },
     { institution: 'UMBOS',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'FELON',
       doctype: 'PD Statement (PD2) BUA',
       drawer: 'UMBUA Lockbox' },
     { institution: 'UMBOS',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'WSAMP',
       doctype: 'Essay BUA',
       drawer: 'UMBUA' },
     { institution: 'UMBOS',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'ESSAY',
       doctype: 'Essay BUA',
       drawer: 'UMBUA' },
     { institution: 'UMBOS',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'REFER',
       doctype: 'Letter of Recommendation BUA',
       drawer: 'UMBUA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'RESUM',
       doctype: 'Resume DUA',
       drawer: 'UMDUA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'PSTMT',
       doctype: 'Personal Statement DUA',
       drawer: 'UMDUA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'DISCL',
       doctype: 'PD Statement (PD1) DUA',
       drawer: 'UMDUA Lockbox' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'FELON',
       doctype: 'PD Statement (PD2) DUA',
       drawer: 'UMDUA Lockbox' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'WSAMP',
       doctype: 'Essay DUA',
       drawer: 'UMDUA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'ESSAY',
       doctype: 'Essay DUA',
       drawer: 'UMDUA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'REFER',
       doctype: 'Letter of Recommendation DUA',
       drawer: 'UMDUA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'CNOW',
       stagedDoctype: 'RESUM',
       doctype: 'Resume DUA',
       drawer: 'UMDUA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'CNOW',
       stagedDoctype: 'PSTMT',
       doctype: 'Personal Statement DUA',
       drawer: 'UMDUA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'CNOW',
       stagedDoctype: 'DISCL',
       doctype: 'PD Statement (PD1) DUA',
       drawer: 'UMDUA Lockbox' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'CNOW',
       stagedDoctype: 'FELON',
       doctype: 'PD Statement (PD2) DUA',
       drawer: 'UMDUA Lockbox' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'CNOW',
       stagedDoctype: 'WSAMP',
       doctype: 'Essay DUA',
       drawer: 'UMDUA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'CNOW',
       stagedDoctype: 'ESSAY',
       doctype: 'Essay DUA',
       drawer: 'UMDUA' },
     { institution: 'UMDAR',
       career: 'UGRD',
       appCenter: 'CNOW',
       stagedDoctype: 'REFER',
       doctype: 'Letter of Recommendation DUA',
       drawer: 'UMDUA' },
     { institution: 'UMLOW',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'RESUM',
       doctype: 'Resume LUA',
       drawer: 'UMLUA' },
     { institution: 'UMLOW',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'PSTMT',
       doctype: 'Personal Statement LUA',
       drawer: 'UMLUA' },
     { institution: 'UMLOW',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'DISCL',
       doctype: 'PD Statement (PD1) LUA',
       drawer: 'UMLUA Lockbox' },
     { institution: 'UMLOW',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'FELON',
       doctype: 'PD Statement (PD2) LUA',
       drawer: 'UMLUA Lockbox' },
     { institution: 'UMLOW',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'WSAMP',
       doctype: 'Essay LUA',
       drawer: 'UMLUA' },
     { institution: 'UMLOW',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'ESSAY',
       doctype: 'Essay LUA',
       drawer: 'UMLUA' },
     { institution: 'UMLOW',
       career: 'UGRD',
       appCenter: 'UGRD',
       stagedDoctype: 'REFER',
       doctype: 'Letter of Recommendation LUA',
       drawer: 'UMLUA' },
     { institution: 'UMBOS',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'RESUM',
       doctype: 'Resume',
       drawer: 'UMBGA' },
     { institution: 'UMBOS',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'PSTMT',
       doctype: 'Statement of Purpose',
       drawer: 'UMBGA' },
     { institution: 'UMBOS',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'DISCL',
       doctype: 'PD Statement (PD1)',
       drawer: 'UMBGA Lockbox' },
     { institution: 'UMBOS',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'FELON',
       doctype: 'PD Statement (PD2)',
       drawer: 'UMBGA Lockbox' },
     { institution: 'UMBOS',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'WSAMP',
       doctype: 'Writing Sample',
       drawer: 'UMBGA' },
     { institution: 'UMBOS',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'ESSAY',
       doctype: 'Statement of Purpose',
       drawer: 'UMBGA' },
     { institution: 'UMBOS',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'REFER',
       doctype: 'Letter of Recommendation',
       drawer: 'UMBGA' },
     { institution: 'UMDAR',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'RESUM',
       doctype: 'Resume',
       drawer: 'UMDGA' },
     { institution: 'UMDAR',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'PSTMT',
       doctype: 'Statement of Purpose',
       drawer: 'UMDGA' },
     { institution: 'UMDAR',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'DISCL',
       doctype: 'PD Statement (PD1)',
       drawer: 'UMDGA Lockbox' },
     { institution: 'UMDAR',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'FELON',
       doctype: 'PD Statement (PD2)',
       drawer: 'UMDGA Lockbox' },
     { institution: 'UMDAR',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'WSAMP',
       doctype: 'Writing Sample',
       drawer: 'UMDGA' },
     { institution: 'UMDAR',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'ESSAY',
       doctype: 'Statement of Purpose',
       drawer: 'UMDGA' },
     { institution: 'UMDAR',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'REFER',
       doctype: 'Letter of Recommendation',
       drawer: 'UMDGA' },
     { institution: 'UMDAR',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'REF1',
       doctype: 'Letter of Recommendation Form DGA',
       drawer: 'UMDGA' },       
     { institution: 'UMLOW',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'RESUM',
       doctype: 'Resume',
       drawer: 'UMLGA' },
     { institution: 'UMLOW',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'PSTMT',
       doctype: 'Statement of Purpose',
       drawer: 'UMLGA' },
     { institution: 'UMLOW',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'DISCL',
       doctype: 'PD Statement (PD1)',
       drawer: 'UMLGA Lockbox' },
     { institution: 'UMLOW',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'FELON',
       doctype: 'PD Statement (PD2)',
       drawer: 'UMLGA Lockbox' },
     { institution: 'UMLOW',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'WSAMP',
       doctype: 'Writing Sample',
       drawer: 'UMLGA' },
     { institution: 'UMLOW',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'ESSAY',
       doctype: 'Statement of Purpose',
       drawer: 'UMLGA' },
     { institution: 'UMLOW',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'REFER',
       doctype: 'Letter of Recommendation',
       drawer: 'UMLGA' },
     { institution: 'UMLOW',
       career: 'GRAD',
       appCenter: 'GRAD',
       stagedDoctype: 'REF1',
       doctype: 'Letter of Recommendation Form LGA',
       drawer: 'UMLGA' },       
     { institution: 'UMLOW',
       career: 'CSCE',
       appCenter: 'CSCE',
       stagedDoctype: 'RESUM',
       doctype: 'Resume',
       drawer: 'UMLUA' },
     { institution: 'UMLOW',
       career: 'CSCE',
       appCenter: 'CSCE',
       stagedDoctype: 'PSTMT',
       doctype: 'Statement of Purpose',
       drawer: 'UMLUA' },
     { institution: 'UMLOW',
       career: 'CSCE',
       appCenter: 'CSCE',
       stagedDoctype: 'DISCL',
       doctype: 'PD Statement (PD1) LUA',
       drawer: 'UMLUA Lockbox' },
     { institution: 'UMLOW',
       career: 'CSCE',
       appCenter: 'CSCE',
       stagedDoctype: 'FELON',
       doctype: 'PD Statement (PD2) LUA',
       drawer: 'UMLUA Lockbox' },
     { institution: 'UMLOW',
       career: 'CSCE',
       appCenter: 'CSCE',
       stagedDoctype: 'WSAMP',
       doctype: 'Writing Sample',
       drawer: 'UMLUA' },
     { institution: 'UMLOW',
       career: 'CSCE',
       appCenter: 'CSCE',
       stagedDoctype: 'ESSAY',
       doctype: 'Statement of Purpose',
       drawer: 'UMLUA' },
     { institution: 'UMLOW',
       career: 'CSCE',
       appCenter: 'CSCE',
       stagedDoctype: 'REFER',
       doctype: 'Letter of Recommendation',
       drawer: 'UMLUA' } ] };

function lookupDrawerDoctypeAD() {
	debug.log('DEBUG', 'running: lookupDrawerDoctypeAD\n');

	var cfg = global.CFG.lookupDrawerDoctypeAD_config;

	if (typeof CUR_CFG.reportName === 'undefined') {
		debug.log('CRITICAL', 'lookupDrawerDoctypeAD: Make sure you define reportName in your report config\n');
		return false;
	}

	if (typeof cfg[CUR_CFG.reportName] !== 'undefined') {
		cfg = cfg[CUR_CFG.reportName];

		var stagedDoctypeOkay;
		var foundMatch = false;

		for (var i = cfg.length - 1; i >= 0; i--) {
			
			// check to see if the optional property exists and if there is a match
			stagedDoctypeOkay = true;
			if (typeof cfg[i].stagedDoctype !== 'undefined') {
				if (STAGE_KEYS.docTypeName !== cfg[i].stagedDoctype) {
					stagedDoctypeOkay = false;
				}
			}
			// check to see if we have a match in our results
			// Type coersion here is intentional
			// probably should create a function to check for these values in any of the staging objects
			var career = getStageValueByName("Career");
			var institution = getStageValueByName("Institution");
			var appCenter = getStageValueByName("App Center");
			if (cfg[i].career == career &&
				cfg[i].institution == institution &&
				cfg[i].appCenter == appCenter &&
				stagedDoctypeOkay) {
				// found a match, time to assign values
				STAGE_KEYS.docTypeName = cfg[i].doctype;
				STAGE_KEYS.drawer = cfg[i].drawer;
				debug.log('DEBUG', 'before break\n');
				foundMatch = true;
				break;
			}
		}
		// log an error if we can't find a matching config
		if (!foundMatch) {
			var errTxt = 'Cannot find a matching config for combination of' +
			'institution:[%s], career:[%s], app center:[%s],' +
			'stagedDoctype:[%s]\n';
			debug.log('ERROR', errTxt, STAGE_NOT_USED.Institution, STAGE_NOT_USED.Career, STAGE_PROPS['App Center'], STAGE_KEYS.docTypeName);
			return false;
		}
	} else {
		debug.log('CRITICAL', 'lookupDrawerDoctypeAD: Cannot find a match for this reportname in config [%s]\n', CUR_CFG.reportName);
		return false;
	}

	// @param {String} name of a property
	// @returns {String|Boolean} value of property, false if can't find
	function getStageValueByName(name) {
		var value;
		if (STAGE_PROPS[name]) {
			return STAGE_PROPS[name];
		} else if (STAGE_NOT_USED[name]) {
			return STAGE_NOT_USED[name];
		} else {
			debug.log('ERROR', 'Can\'t find [%s] in STAGE objects\n');
			return false;
		}
	}

	return true;
}
	
